#!/bin/bash

file=$1
while read num
do
	factors=($(factor $num))
	if (($num < 2**63));
	then
		div=$((num/factors[1]))
	else
		div=$(echo "0 k $num ${factors[1]} / n" | dc)
	fi;
	echo "$num=$div*${factors[1]}"
done < $file
